# 데이터 합치기

In [1]:
import pandas as pd

df1 = pd.read_excel('./EU크롤링/84/eu_1213_84_df.xlsx')
df2 = pd.read_excel('./EU크롤링/84/84EU1415_page_.xlsx')
df3 = pd.read_excel('./EU크롤링/84/84_16_17_EU.xlsx')
df4 = pd.read_excel('./EU크롤링/84/EU_84_1819_df.xlsx')
df5 = pd.read_excel('./EU크롤링/84/84_EU_2021_df_total.xlsx')
df6 = pd.read_excel('./EU크롤링/84/84_22_23_EU.xlsx')

In [2]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5248 entries, 0 to 5247
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0.1  5248 non-null   int64 
 1   Unnamed: 0    5248 non-null   int64 
 2   hs code       5248 non-null   int64 
 3   keyword       5071 non-null   object
 4   description   5248 non-null   object
 5   reason        5246 non-null   object
dtypes: int64(3), object(3)
memory usage: 246.1+ KB


In [3]:
df1.drop('Unnamed: 0.1', axis=1, inplace=True)
df1.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
df1.columns = ['hs code', 'product', 'description', 'reason']

In [9]:
df1.isna().sum()

hs code        0
product        0
description    0
reason         0
dtype: int64

In [6]:
df1['product'].fillna(' ', inplace=True)

In [8]:
df1.dropna(inplace=True)

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5246 entries, 0 to 5247
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   hs code      5246 non-null   int64 
 1   product      5246 non-null   object
 2   description  5246 non-null   object
 3   reason       5246 non-null   object
dtypes: int64(1), object(3)
memory usage: 204.9+ KB


In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5446 entries, 0 to 5445
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   5446 non-null   int64 
 1   hs code      5446 non-null   int64 
 2   product      5341 non-null   object
 3   description  5446 non-null   object
 4   reason       5446 non-null   object
dtypes: int64(2), object(3)
memory usage: 212.9+ KB


In [12]:
df2.drop('Unnamed: 0', axis=1, inplace=True)

In [15]:
df2.isna().sum()

hs code        0
product        0
description    0
reason         0
dtype: int64

In [14]:
df2['product'].fillna(' ', inplace=True)

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5446 entries, 0 to 5445
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   hs code      5446 non-null   int64 
 1   product      5446 non-null   object
 2   description  5446 non-null   object
 3   reason       5446 non-null   object
dtypes: int64(1), object(3)
memory usage: 170.3+ KB


In [21]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6394 entries, 0 to 6393
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   hs code      6394 non-null   int64 
 1   product      6394 non-null   object
 2   description  6394 non-null   object
 3   reason       6394 non-null   object
dtypes: int64(1), object(3)
memory usage: 199.9+ KB


In [18]:
df3.drop('Unnamed: 0', axis=1, inplace=True)

In [19]:
df3.isna().sum()

hs code         0
product        55
description     0
reason          0
dtype: int64

In [20]:
df3['product'].fillna(' ', inplace=True)

In [22]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6900 entries, 0 to 6899
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0.1  6900 non-null   int64 
 1   Unnamed: 0    6900 non-null   int64 
 2   hs code       6900 non-null   object
 3   description   6900 non-null   object
 4   reason        6898 non-null   object
 5   product       6869 non-null   object
dtypes: int64(2), object(4)
memory usage: 323.6+ KB


In [23]:
df4.drop('Unnamed: 0.1', axis=1, inplace=True)
df4.drop('Unnamed: 0', axis=1, inplace=True)

In [28]:
df4.isna().sum()

hs code        0
description    0
reason         0
product        0
dtype: int64

In [25]:
df4['product'].fillna(' ', inplace=True)

In [27]:
df4.dropna(inplace=True)

In [29]:
df4 = df4[['hs code', 'product', 'description', 'reason']]

In [30]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4940 entries, 0 to 4939
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   4940 non-null   int64 
 1   hs code      4940 non-null   object
 2   product      4940 non-null   object
 3   description  4940 non-null   object
 4   reason       4940 non-null   object
dtypes: int64(1), object(4)
memory usage: 193.1+ KB


In [31]:
df5.drop('Unnamed: 0', axis=1, inplace=True)

In [32]:
df5.isna().sum()

hs code        0
product        0
description    0
reason         0
dtype: int64

In [33]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5648 entries, 0 to 5647
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   5648 non-null   int64 
 1   hs code      5648 non-null   object
 2   product      5644 non-null   object
 3   description  5645 non-null   object
 4   reason       5647 non-null   object
dtypes: int64(1), object(4)
memory usage: 220.8+ KB


In [34]:
df6.drop('Unnamed: 0', axis=1, inplace=True)

In [35]:
df6.isna().sum()

hs code        0
product        4
description    3
reason         1
dtype: int64

In [36]:
df6.dropna(inplace=True)

In [37]:
eu_df = pd.concat([df1, df2, df3, df4, df5, df6])
eu_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34566 entries, 0 to 5647
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   hs code      34566 non-null  object
 1   product      34566 non-null  object
 2   description  34566 non-null  object
 3   reason       34566 non-null  object
dtypes: object(4)
memory usage: 1.3+ MB


In [38]:
uk_df = pd.read_excel('./EU크롤링/84/84df_UK (1).xlsx')
uk_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2138 entries, 0 to 2137
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   2138 non-null   int64 
 1   hs code      2138 non-null   int64 
 2   product      2138 non-null   object
 3   description  2138 non-null   object
 4   reason       2138 non-null   object
dtypes: int64(2), object(3)
memory usage: 83.6+ KB


In [39]:
uk_df.drop('Unnamed: 0', axis=1, inplace=True)

In [40]:
ko_df = pd.read_excel('./EU크롤링/84/final84.xlsx')
ko_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3868 entries, 0 to 3867
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   3868 non-null   int64 
 1   hs code      3868 non-null   int64 
 2   product      3868 non-null   object
 3   description  3868 non-null   object
 4   reason       3868 non-null   object
dtypes: int64(2), object(3)
memory usage: 151.2+ KB


In [41]:
ko_df.drop('Unnamed: 0', axis=1, inplace=True)

In [42]:
total_df = pd.concat([eu_df, uk_df, ko_df])
total_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40572 entries, 0 to 3867
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   hs code      40572 non-null  object
 1   product      40572 non-null  object
 2   description  40572 non-null  object
 3   reason       40572 non-null  object
dtypes: object(4)
memory usage: 1.5+ MB


# 데이터 전처리

In [49]:
total_df

hs code                                            product  \
0       8414                                         TABLE FANS   
1       8470  CASH REGISTERS, HARD DISCS, WITH USB SLOT, VAR...   
2       8479       DRIVE MECHANISMS, KARABINERS, OF ALLOY STEEL   
3       8467  PNEUMATIC TOOLS, ROTARY, WITH END PART, SOCKET...   
4       8457                                  MACHINING CENTRES   
...      ...                                                ...   
3863    8485                   tube handle for ovens and ranges   
3864    8485                                    grease fittings   
3865    8485                             adhesive dispense tips   
3866    8453  Machinery for preparing, tanning or working hi...   
3867    8453         Machinery for making or repairing footwear   

                                            description  \
0     Table fan, a built-in power 35 W.Dimensions el...   
1     TERMINAL OF SALE IN THE FORM OF PORTABLE WHOSE...   
2     MECHANISM FALL MOBILE STEEL ALLIE.IL IS HAVING...   
3     ROTARY AIR TOOL IN THE FORM OF REVERSIBLE RATC...   
4     Machining center with horizontal spindle hard ...   
...                                                 ...   
3863  The article in question is described as a stai...   
3864  A descriptive brochure and samples of various ...   
3865  The articles in question are described as disp...   
3866  machinery for preparing hides or skins (includ...   
3867  machinery used for making or repairing article...   

                                                 reason  
0     General Rules 1 and 6: The classification is d...  
1     General Rules 1 and 6: The classification is d...  
2     General Rules 1 and 6: The classification is d...  
3     General Rules 1 and 6: The classification is d...  
4     General Rules 1 and 6: The classification is d...  
...                                                 ...  
3863  The applicable subheading for the oven/range h...  
3864  The applicable subheading for the grease fitti...  
3865  The applicable subheading for the dispense tip...  
3866  84.53 Machinery for preparing, tanning or work...  
3867  84.53 Machinery for preparing, tanning or work...  

[40572 rows x 4 columns]

In [44]:
def check_code(code):
    p = re.compile('84\d\d')  # 84로 시작하는 패턴
    m = p.match(str(code))  # hs코드에서 패턴에 맞는 거 찾기 
    
    if m == None:  # 패턴에 맞지 않는 경우(패턴에 맞지 않으면 none 출력)
        return None  # 패턴에 맞지 않으면 na값으로 반환
    
    else:  # 패턴에 맞는 경우
        return m.group()  # 패턴에 맞는 코드(4자리수) 반환

In [45]:
import re
total_df['hs code'] = total_df['hs code'].apply(lambda x : check_code(x))

In [46]:
total_df

hs code                                            product  \
0       8414                                         TABLE FANS   
1       8470  CASH REGISTERS, HARD DISCS, WITH USB SLOT, VAR...   
2       8479       DRIVE MECHANISMS, KARABINERS, OF ALLOY STEEL   
3       8467  PNEUMATIC TOOLS, ROTARY, WITH END PART, SOCKET...   
4       8457                                  MACHINING CENTRES   
...      ...                                                ...   
3863    8485                   tube handle for ovens and ranges   
3864    8485                                    grease fittings   
3865    8485                             adhesive dispense tips   
3866    8453  Machinery for preparing, tanning or working hi...   
3867    8453         Machinery for making or repairing footwear   

                                            description  \
0     Table fan, a built-in power 35 W.Dimensions el...   
1     TERMINAL OF SALE IN THE FORM OF PORTABLE WHOSE...   
2     MECHANISM FALL MOBILE STEEL ALLIE.IL IS HAVING...   
3     ROTARY AIR TOOL IN THE FORM OF REVERSIBLE RATC...   
4     Machining center with horizontal spindle hard ...   
...                                                 ...   
3863  The article in question is described as a stai...   
3864  A descriptive brochure and samples of various ...   
3865  The articles in question are described as disp...   
3866  machinery for preparing hides or skins (includ...   
3867  machinery used for making or repairing article...   

                                                 reason  
0     General Rules 1 and 6: The classification is d...  
1     General Rules 1 and 6: The classification is d...  
2     General Rules 1 and 6: The classification is d...  
3     General Rules 1 and 6: The classification is d...  
4     General Rules 1 and 6: The classification is d...  
...                                                 ...  
3863  The applicable subheading for the oven/range h...  
3864  The applicable subheading for the grease fitti...  
3865  The applicable subheading for the dispense tip...  
3866  84.53 Machinery for preparing, tanning or work...  
3867  84.53 Machinery for preparing, tanning or work...  

[40572 rows x 4 columns]

In [53]:
total_df.isna().sum()

hs code        0
product        0
description    0
reason         0
dtype: int64

In [52]:
total_df.dropna(inplace=True)

In [54]:
total_df['name_des']=total_df['product']+' '+total_df['description']

In [55]:
total_df

hs code                                            product  \
0       8414                                         TABLE FANS   
1       8470  CASH REGISTERS, HARD DISCS, WITH USB SLOT, VAR...   
2       8479       DRIVE MECHANISMS, KARABINERS, OF ALLOY STEEL   
3       8467  PNEUMATIC TOOLS, ROTARY, WITH END PART, SOCKET...   
4       8457                                  MACHINING CENTRES   
...      ...                                                ...   
3863    8485                   tube handle for ovens and ranges   
3864    8485                                    grease fittings   
3865    8485                             adhesive dispense tips   
3866    8453  Machinery for preparing, tanning or working hi...   
3867    8453         Machinery for making or repairing footwear   

                                            description  \
0     Table fan, a built-in power 35 W.Dimensions el...   
1     TERMINAL OF SALE IN THE FORM OF PORTABLE WHOSE...   
2     MECHANISM FALL MOBILE STEEL ALLIE.IL IS HAVING...   
3     ROTARY AIR TOOL IN THE FORM OF REVERSIBLE RATC...   
4     Machining center with horizontal spindle hard ...   
...                                                 ...   
3863  The article in question is described as a stai...   
3864  A descriptive brochure and samples of various ...   
3865  The articles in question are described as disp...   
3866  machinery for preparing hides or skins (includ...   
3867  machinery used for making or repairing article...   

                                                 reason  \
0     General Rules 1 and 6: The classification is d...   
1     General Rules 1 and 6: The classification is d...   
2     General Rules 1 and 6: The classification is d...   
3     General Rules 1 and 6: The classification is d...   
4     General Rules 1 and 6: The classification is d...   
...                                                 ...   
3863  The applicable subheading for the oven/range h...   
3864  The applicable subheading for the grease fitti...   
3865  The applicable subheading for the dispense tip...   
3866  84.53 Machinery for preparing, tanning or work...   
3867  84.53 Machinery for preparing, tanning or work...   

                                               name_des  
0     TABLE FANS Table fan, a built-in power 35 W.Di...  
1     CASH REGISTERS, HARD DISCS, WITH USB SLOT, VAR...  
2     DRIVE MECHANISMS, KARABINERS, OF ALLOY STEEL M...  
3     PNEUMATIC TOOLS, ROTARY, WITH END PART, SOCKET...  
4     MACHINING CENTRES Machining center with horizo...  
...                                                 ...  
3863  tube handle for ovens and ranges The article i...  
3864  grease fittings A descriptive brochure and sam...  
3865  adhesive dispense tips The articles in questio...  
3866  Machinery for preparing, tanning or working hi...  
3867  Machinery for making or repairing footwear mac...  

[39672 rows x 5 columns]

In [119]:
total_df.to_excel('total_84.xlsx')

In [1]:
import pandas as pd

total_df = pd.read_excel('./EU크롤링/84/total_84.xlsx')
total_df.head()

Unnamed: 0  ...                                           name_des
0           0  ...  TABLE FANS Table fan, a built-in power 35 W.Di...
1           1  ...  CASH REGISTERS, HARD DISCS, WITH USB SLOT, VAR...
2           2  ...  DRIVE MECHANISMS, KARABINERS, OF ALLOY STEEL M...
3           3  ...  PNEUMATIC TOOLS, ROTARY, WITH END PART, SOCKET...
4           4  ...  MACHINING CENTRES Machining center with horizo...

[5 rows x 6 columns]

In [2]:
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39672 entries, 0 to 39671
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   39672 non-null  int64 
 1   hs code      39672 non-null  int64 
 2   product      39672 non-null  object
 3   description  39672 non-null  object
 4   reason       39672 non-null  object
 5   name_des     39672 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.8+ MB


In [3]:
total_df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
from sklearn.model_selection import train_test_split
import re

x = total_df['name_des'].apply(lambda x: re.sub('[^a-zA-Z]',' ',x))
y = total_df['hs code'].astype(int)
z = total_df['reason'].apply(lambda x: re.sub('[^a-zA-Z]',' ',x))

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=10)

print(len(x_train))
print(len(x_test))

x_train = pd.concat([x_train, z])
y_train = pd.concat([y_train, y])

print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(x_test))

31737
7935
71409
71409
7935
7935


In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk import sent_tokenize
from nltk import word_tokenize
import nltk
import string
from nltk.stem import WordNetLemmatizer
import nltk

stopwords = nltk.corpus.stopwords.words('english')
# 특수문자
string = string.punctuation
# 불용어 + 특수문자 합친 리스트 생성
for stri in string:
    stopwords.append(stri)

token_list = None
def text_preprocessing(text):
    # 어근 추출 객체 생성
    lemmar = WordNetLemmatizer()
    global token_list
    # 텍스트를 소문자로 변환 후 문장으로 토큰화
    sentences = sent_tokenize(text.lower())

    for sentence in sentences:        
        # 단어로 토큰화
        tokens = word_tokenize(sentence)
        # 토큰화된 단어들의 어근 추출
        token_list = [lemmar.lemmatize(token) for token in tokens]

    return token_list

tfidf_vec = TfidfVectorizer(tokenizer=text_preprocessing, stop_words = stopwords)
tfidf_vec.fit(x_train)
x_train_tfidf_vec = tfidf_vec.transform(x_train) 

x_test_tfidf_vec = tfidf_vec.transform(x_test)
y_test = y_test.apply(pd.to_numeric, errors='coerce')

C:\Users\user\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", '``', 'could', 'doe', 'ha', 'might', 'must', "n't", 'need', 'sha', 'wa', 'wo', 'would'] not in stop_words.
  warnings.warn(


In [59]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score

svc = LinearSVC(C=1)
svc.fit(x_train_tfidf_vec,y_train)

y_hat = svc.predict(x_test_tfidf_vec)

print(f'정확도: {accuracy_score(y_test, y_hat):.3f}')
print(f'정밀도: {precision_score(y_test, y_hat, average="weighted"):.3f}')
print(f'재현율: {recall_score(y_test, y_hat, average="weighted"):.3f}')

정확도: 0.933
정밀도: 0.933
재현율: 0.933


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [61]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

        8401       1.00      1.00      1.00         3
        8402       0.75      0.75      0.75         4
        8403       0.82      1.00      0.90         9
        8404       0.00      0.00      0.00         2
        8405       1.00      0.50      0.67         4
        8406       1.00      1.00      1.00         1
        8407       1.00      0.44      0.62         9
        8408       0.83      0.71      0.77         7
        8409       0.90      0.96      0.93       162
        8410       0.00      0.00      0.00         1
        8411       0.89      0.95      0.92        60
        8412       0.87      0.87      0.87       102
        8413       0.94      0.94      0.94       248
        8414       0.93      0.93      0.93       355
        8415       0.89      0.91      0.90        90
        8416       1.00      1.00      1.00         5
        8417       1.00      0.90      0.95        21
        8418       0.98    

C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
test = pd.read_excel('84미국사례 테스트용.xlsx')
test.head()

hs code                                        description
0     8481  The Cooler Keg, model number CK0001, is referr...
1     8470  The products under consideration are identifie...
2     8428  The merchandise under consideration is describ...
3     8445  At issue is the GlassTwister ring twisting mac...
4     8415  The air handler unit in question is available ...

In [14]:
x_test_test_tfidf_vec = tfidf_vec.transform(test['description'])

In [63]:
y_hat_hat = svc.predict(x_test_test_tfidf_vec)

y_hat_hat

array([8422, 8473, 8431, 8414, 8481, 8471, 8483, 8479, 8483, 8414, 8428,
       8419, 8471, 8479, 8486, 8479, 8428, 8481, 8421, 8431])

In [65]:
test['hs code'].values

array([8481, 8470, 8428, 8445, 8415, 8424, 8482, 8462, 8466, 8414, 8427,
       8421, 8473, 8419, 8479, 8422, 8431, 8481, 8421, 8431], dtype=int64)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

lr = LogisticRegression(solver='saga', multi_class='multinomial', C=3)
lr.fit(x_train_tfidf_vec,y_train)

y_hat = lr.predict(x_test_tfidf_vec)

print(f'정확도: {accuracy_score(y_test, y_hat):.3f}')
print(f'정밀도: {precision_score(y_test, y_hat, average="weighted"):.3f}')
print(f'재현율: {recall_score(y_test, y_hat, average="weighted"):.3f}')

정확도: 0.918
정밀도: 0.919
재현율: 0.918


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [130]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

        8401       0.00      0.00      0.00         3
        8402       0.00      0.00      0.00         4
        8403       1.00      0.22      0.36         9
        8404       0.00      0.00      0.00         2
        8405       0.00      0.00      0.00         4
        8406       0.00      0.00      0.00         1
        8407       0.00      0.00      0.00         9
        8408       1.00      0.29      0.44         7
        8409       0.88      0.93      0.91       162
        8410       0.00      0.00      0.00         1
        8411       0.84      0.90      0.87        60
        8412       0.83      0.83      0.83       102
        8413       0.90      0.94      0.92       248
        8414       0.88      0.90      0.89       355
        8415       0.89      0.86      0.87        90
        8416       1.00      0.20      0.33         5
        8417       1.00      0.71      0.83        21
        8418       0.97    

C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
y_hat_hat = lr.predict(x_test_test_tfidf_vec)

y_hat_hat

array([8422, 8424, 8428, 8479, 8481, 8479, 8479, 8479, 8481, 8414, 8428,
       8419, 8471, 8479, 8479, 8479, 8428, 8481, 8421, 8431])

In [11]:
test['hs code'].values

array([8481, 8470, 8428, 8445, 8415, 8424, 8482, 8462, 8466, 8414, 8427,
       8421, 8473, 8419, 8479, 8422, 8431, 8481, 8421, 8431], dtype=int64)

In [76]:
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(precision=6, suppress=True)

In [87]:
y = total_df['hs code'].unique()
y.sort()

In [88]:
y

array(['8401', '8402', '8403', '8404', '8405', '8406', '8407', '8408',
       '8409', '8410', '8411', '8412', '8413', '8414', '8415', '8416',
       '8417', '8418', '8419', '8420', '8421', '8422', '8423', '8424',
       '8425', '8426', '8427', '8428', '8429', '8430', '8431', '8432',
       '8433', '8434', '8435', '8436', '8437', '8438', '8439', '8440',
       '8441', '8442', '8443', '8444', '8445', '8446', '8447', '8448',
       '8449', '8450', '8451', '8452', '8453', '8454', '8455', '8456',
       '8457', '8458', '8459', '8460', '8461', '8462', '8463', '8464',
       '8465', '8466', '8467', '8468', '8470', '8471', '8472', '8473',
       '8474', '8475', '8476', '8477', '8478', '8479', '8480', '8481',
       '8482', '8483', '8484', '8485', '8486', '8487'], dtype=object)

In [83]:
lr.predict_proba(x_test_test_tfidf_vec)

array([[0.001502, 0.001797, 0.003033, 0.001289, 0.002297, 0.000913,
        0.002945, 0.002412, 0.012621, 0.000731, 0.007002, 0.010238,
        0.013494, 0.024958, 0.00782 , 0.00233 , 0.00364 , 0.024847,
        0.030872, 0.001989, 0.033429, 0.115029, 0.009152, 0.029164,
        0.011105, 0.004904, 0.007094, 0.02857 , 0.002878, 0.006312,
        0.030211, 0.012726, 0.012331, 0.000919, 0.001348, 0.010872,
        0.000733, 0.023   , 0.003174, 0.000732, 0.004123, 0.001959,
        0.017392, 0.000827, 0.001741, 0.000544, 0.001017, 0.003662,
        0.00093 , 0.002879, 0.006139, 0.002723, 0.00083 , 0.003145,
        0.001115, 0.005817, 0.001751, 0.001296, 0.002387, 0.003463,
        0.001827, 0.007603, 0.001293, 0.003489, 0.005812, 0.012436,
        0.014397, 0.002009, 0.006858, 0.050082, 0.009721, 0.024306,
        0.008307, 0.001112, 0.003341, 0.009819, 0.002063, 0.103474,
        0.006031, 0.086703, 0.007524, 0.031535, 0.007066, 0.002463,
        0.014205, 0.01237 ],
       [0.001357, 0

In [89]:
p_proba = pd.DataFrame(lr.predict_proba(x_test_test_tfidf_vec), columns=y)

In [90]:
p_proba

8401      8402      8403      8404      8405      8406      8407  \
0   0.001502  0.001797  0.003033  0.001289  0.002297  0.000913  0.002945   
1   0.001357  0.001623  0.002625  0.001181  0.002166  0.000832  0.002722   
2   0.001099  0.001314  0.002133  0.000955  0.001549  0.000661  0.002059   
3   0.001423  0.001666  0.002985  0.001211  0.002082  0.000878  0.003005   
4   0.000741  0.000938  0.002353  0.000880  0.001211  0.000466  0.001587   
5   0.001492  0.001810  0.003104  0.001351  0.002187  0.000911  0.003145   
6   0.001274  0.001526  0.002588  0.001106  0.001859  0.000811  0.002475   
7   0.001636  0.002001  0.003442  0.001476  0.002275  0.000944  0.002923   
8   0.001333  0.001616  0.004804  0.001224  0.001977  0.000864  0.002559   
9   0.001450  0.001866  0.002853  0.001287  0.002113  0.000910  0.003114   
10  0.001312  0.001488  0.002466  0.001084  0.001832  0.000765  0.002382   
11  0.001479  0.001796  0.003069  0.001296  0.002326  0.000913  0.002877   
12  0.000748  0.000929  0.001483  0.000658  0.001205  0.000461  0.001477   
13  0.001583  0.001960  0.003206  0.001404  0.002472  0.000976  0.003056   
14  0.001599  0.001914  0.003256  0.001371  0.002294  0.000970  0.003139   
15  0.000954  0.001144  0.002076  0.000833  0.001333  0.000622  0.001723   
16  0.001238  0.001503  0.002603  0.001080  0.001823  0.000760  0.002690   
17  0.000390  0.000503  0.000758  0.000363  0.000572  0.000240  0.000725   
18  0.000646  0.000769  0.001530  0.000533  0.000980  0.000360  0.002969   
19  0.001467  0.001758  0.003107  0.001271  0.002297  0.000900  0.002847   

        8408      8409      8410  ...      8478      8479      8480      8481  \
0   0.002412  0.012621  0.000731  ...  0.002063  0.103474  0.006031  0.086703   
1   0.002104  0.008325  0.000679  ...  0.002136  0.144649  0.004970  0.030986   
2   0.001641  0.007015  0.000540  ...  0.001431  0.124890  0.004720  0.022023   
3   0.002365  0.014518  0.000699  ...  0.001883  0.217076  0.005502  0.029026   
4   0.001195  0.008343  0.000376  ...  0.001040  0.061106  0.002595  0.261757   
5   0.002487  0.011284  0.000753  ...  0.002015  0.162130  0.006627  0.049845   
6   0.002070  0.013070  0.000632  ...  0.001943  0.165014  0.005245  0.030095   
7   0.002423  0.011842  0.000758  ...  0.002337  0.160371  0.006612  0.032167   
8   0.002081  0.017453  0.000664  ...  0.001950  0.078342  0.005794  0.076256   
9   0.002346  0.011591  0.000709  ...  0.001943  0.158715  0.005840  0.068922   
10  0.001961  0.010617  0.000614  ...  0.001729  0.106204  0.004791  0.027321   
11  0.002483  0.011166  0.000735  ...  0.002135  0.117175  0.006015  0.038213   
12  0.001232  0.006437  0.000373  ...  0.001044  0.040166  0.002928  0.016488   
13  0.002518  0.013488  0.000775  ...  0.002283  0.168567  0.006244  0.045307   
14  0.002571  0.013504  0.000776  ...  0.002201  0.143173  0.006449  0.040529   
15  0.001437  0.006934  0.000485  ...  0.001467  0.452035  0.004901  0.037902   
16  0.001958  0.011017  0.000617  ...  0.001695  0.171098  0.005048  0.037882   
17  0.000607  0.008181  0.000189  ...  0.000520  0.034673  0.001521  0.782864   
18  0.001609  0.043724  0.000291  ...  0.000847  0.026042  0.002628  0.011670   
19  0.002433  0.011436  0.000721  ...  0.001984  0.125309  0.005771  0.035276   

        8482      8483      8484      8485      8486      8487  
0   0.007524  0.031535  0.007066  0.002463  0.014205  0.012370  
1   0.006217  0.022512  0.005753  0.002145  0.017058  0.011126  
2   0.004380  0.014823  0.004596  0.001630  0.013083  0.013003  
3   0.005489  0.071913  0.006576  0.001967  0.014032  0.011253  
4   0.003373  0.009555  0.003118  0.001103  0.006584  0.005348  
5   0.008844  0.034496  0.008279  0.002450  0.016356  0.017636  
6   0.006911  0.195643  0.007693  0.002069  0.011302  0.013537  
7   0.007625  0.026713  0.006888  0.002285  0.017261  0.017796  
8   0.005187  0.170000  0.006733  0.001911  0.011061  0.045822  
9   0.007219  0.020358  0.006729  0.002337  0.014873  0.011

In [91]:
p_proba.to_excel('84_predict_proba.xlsx')

In [100]:
test['hs code'].values

array([8481, 8470, 8428, 8445, 8415, 8424, 8482, 8462, 8466, 8414, 8427,
       8421, 8473, 8419, 8479, 8422, 8431, 8481, 8421, 8431], dtype=int64)

In [97]:
# 8481
p_proba.iloc[0].sort_values(ascending=False)[:3]

8422    0.115029
8479    0.103474
8481    0.086703
Name: 0, dtype: float64

In [98]:
# 8470
p_proba.iloc[1].sort_values(ascending=False)[:3]

8479    0.144649
8467    0.110955
8473    0.070153
Name: 1, dtype: float64

In [101]:
# 8428
p_proba.iloc[2].sort_values(ascending=False)[:3]

8428    0.231833
8431    0.132374
8479    0.124890
Name: 2, dtype: float64

In [102]:
# 8445
p_proba.iloc[3].sort_values(ascending=False)[:3]

8479    0.217076
8483    0.071913
8414    0.057761
Name: 3, dtype: float64

In [103]:
# 8415
p_proba.iloc[4].sort_values(ascending=False)[:3]

8481    0.261757
8419    0.218855
8414    0.088995
Name: 4, dtype: float64

In [106]:
# 8424
p_proba.iloc[5].sort_values(ascending=False)[:3]

8479    0.162130
8471    0.064392
8431    0.054702
Name: 5, dtype: float64

In [107]:
# 8482
p_proba.iloc[6].sort_values(ascending=False)[:3]

8483    0.195643
8479    0.165014
8473    0.049865
Name: 6, dtype: float64

In [108]:
# 8462
p_proba.iloc[7].sort_values(ascending=False)[:3]

8479    0.160371
8424    0.071423
8419    0.057592
Name: 7, dtype: float64

In [109]:
# 8466
p_proba.iloc[8].sort_values(ascending=False)[:3]

8483    0.170000
8479    0.078342
8481    0.076256
Name: 8, dtype: float64

In [110]:
# 8414
p_proba.iloc[9].sort_values(ascending=False)[:3]

8479    0.158715
8414    0.091120
8481    0.068922
Name: 9, dtype: float64

In [111]:
# 8427
p_proba.iloc[10].sort_values(ascending=False)[:3]

8428    0.190686
8431    0.133357
8479    0.106204
Name: 10, dtype: float64

In [112]:
# 8421
p_proba.iloc[11].sort_values(ascending=False)[:3]

8479    0.117175
8419    0.089798
8471    0.076927
Name: 11, dtype: float64

In [113]:
# 8473
p_proba.iloc[12].sort_values(ascending=False)[:3]

8471    0.565402
8473    0.052800
8479    0.040166
Name: 12, dtype: float64

In [114]:
# 8419
p_proba.iloc[13].sort_values(ascending=False)[:3]

8479    0.168567
8481    0.045307
8419    0.041525
Name: 13, dtype: float64

In [115]:
# 8479
p_proba.iloc[14].sort_values(ascending=False)[:3]

8479    0.143173
8486    0.071504
8421    0.041836
Name: 14, dtype: float64

In [116]:
# 8422
p_proba.iloc[15].sort_values(ascending=False)[:3]

8479    0.452035
8472    0.042467
8481    0.037902
Name: 15, dtype: float64

In [117]:
# 8431
p_proba.iloc[16].sort_values(ascending=False)[:3]

8479    0.171098
8428    0.166648
8431    0.094915
Name: 16, dtype: float64

In [12]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score

sv = SVC(kernel='poly', C=3)
sv.fit(x_train_tfidf_vec,y_train)

y_hat = sv.predict(x_test_tfidf_vec)

print(f'정확도: {accuracy_score(y_test, y_hat):.3f}')
print(f'정밀도: {precision_score(y_test, y_hat, average="weighted"):.3f}')
print(f'재현율: {recall_score(y_test, y_hat, average="weighted"):.3f}')

정확도: 0.812
정밀도: 0.908
재현율: 0.812


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
from sklearn.multiclass import OneVsRestClassifier

ovr_clf = OneVsRestClassifier(SVC())
ovr_clf.fit(x_train_tfidf_vec,y_train)
y_hat = sv.predict(x_test_tfidf_vec)

print(f'정확도: {accuracy_score(y_test, y_hat):.3f}')
print(f'정밀도: {precision_score(y_test, y_hat, average="weighted"):.3f}')
print(f'재현율: {recall_score(y_test, y_hat, average="weighted"):.3f}')

정확도: 0.812
정밀도: 0.908
재현율: 0.812


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
y_real_hat = ovr_clf.predict(x_test_test_tfidf_vec)

y_real_hat

array([8422, 8467, 8428, 8479, 8419, 8471, 8483, 8479, 8483, 8414, 8428,
       8419, 8471, 8479, 8486, 8479, 8428, 8481, 8421, 8431])

In [17]:
test['hs code'].values

array([8481, 8470, 8428, 8445, 8415, 8424, 8482, 8462, 8466, 8414, 8427,
       8421, 8473, 8419, 8479, 8422, 8431, 8481, 8421, 8431], dtype=int64)

In [21]:
test2 = pd.read_excel('EU84_TEST.xlsx')
test2

hs code                                        description
0     8479  ELECTRIC,MOTOR VEHICLE PARTS, undertow. electr...
1     8486  SECTIONS,FOR SEMICONDUCTOR PRODUCTION,CABLES u...
2     8473  PORTABLE,TRIVETS,CENTRIFUGAL FANS,NOTEBOOK COM...
3     8486  SECTIONS,OF STEEL,FOR SEMICONDUCTOR PRODUCTION...
4     8462  MONTREUIL BENDING DIGITAL CONTROL FOR PERFORMI...
5     8467  SAWS,FOR WORKING IN THE HAND,WITH ELECTRIC MOT...
6     8471  ADAPTERS,PRINTED CIRCUITS,CONNECTIONS,COMPUTER...
7     8471  PRINTED CIRCUITS,CONNECTIONS,COMPUTER INTERFAC...
8     8467  SANDERS,WITH ELECTRIC MOTOR,FOR WORKING IN THE...
9     8467  SAWS,FOR WORKING IN THE HAND,WITH ELECTRIC MOT...

In [22]:
x_test_test2_tfidf_vec = tfidf_vec.transform(test2['description'])

In [23]:
y_hat_hat2 = ovr_clf.predict(x_test_test2_tfidf_vec)

y_hat_hat2

array([8479, 8486, 8473, 8486, 8462, 8467, 8479, 8471, 8467, 8467])

In [24]:
test2['hs code'].values

array([8479, 8486, 8473, 8486, 8462, 8467, 8471, 8471, 8467, 8467],
      dtype=int64)

In [131]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(x_train_tfidf_vec,y_train)

y_hat = nb.predict(x_test_tfidf_vec)

print(f'정확도: {accuracy_score(y_test, y_hat):.3f}')
print(f'정밀도: {precision_score(y_test, y_hat, average="weighted"):.3f}')
print(f'재현율: {recall_score(y_test, y_hat, average="weighted"):.3f}')

정확도: 0.634
정밀도: 0.724
재현율: 0.634


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [132]:
y_hat_hat = nb.predict(x_test_test_tfidf_vec)

y_hat_hat

array([8481, 8471, 8479, 8479, 8479, 8471, 8483, 8479, 8481, 8481, 8428,
       8479, 8471, 8479, 8479, 8479, 8479, 8481, 8421, 8431])

In [133]:
test['hs code'].values

array([8481, 8470, 8428, 8445, 8415, 8424, 8482, 8462, 8466, 8414, 8427,
       8421, 8473, 8419, 8479, 8422, 8431, 8481, 8421, 8431], dtype=int64)

In [134]:
test2 = pd.read_excel('8479.xlsx')
test2

8479  \
0  8479   
1  8479   
2  8479   
3  8479   
4  8481   
5  8481   
6  8481   
7  8481   
8  8481   

  The IBC Brand Cleaning Tool, Standard Series, for SC, ST, FC, and E2000 Connectors, part # 9392, is a tool used for cleaning various single fiber connectors. It is composed of antistatic resin and has an extendable tip for reaching recessed connectors. The cleaning tip has densely stranded micro fibers that do not require any solvent as they sweep contaminants from the connector. It can be used for removing Arizona road dust, dryer lint, skin oil, pre- and post-mate graphite, 70% IPA residue, distilled water residue, hand lotion, NaCl residue, etc., on fibre optic connectors used in fiber network panels and assemblies, outdoor FTTX applications, servers, switches, routers, etc.  
0  The UHD-III ROV (remotely operated vehicle) is...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
1  As per the information received, the esthetic ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
2  The "K-9 Kannon, P/N 49213" is a tennis ball l...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
3  The good is called the Cobra MK-II and is manu...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
4  This is a plastic, replacement spout for vario...                                                                                                                                                                                                                                                                                                                                                                                                 

In [139]:
test2.loc[9]=test2.columns.values

In [140]:
test2

8479  \
0  8479   
1  8479   
2  8479   
3  8479   
4  8481   
5  8481   
6  8481   
7  8481   
8  8481   
9  8479   

  The IBC Brand Cleaning Tool, Standard Series, for SC, ST, FC, and E2000 Connectors, part # 9392, is a tool used for cleaning various single fiber connectors. It is composed of antistatic resin and has an extendable tip for reaching recessed connectors. The cleaning tip has densely stranded micro fibers that do not require any solvent as they sweep contaminants from the connector. It can be used for removing Arizona road dust, dryer lint, skin oil, pre- and post-mate graphite, 70% IPA residue, distilled water residue, hand lotion, NaCl residue, etc., on fibre optic connectors used in fiber network panels and assemblies, outdoor FTTX applications, servers, switches, routers, etc.  
0  The UHD-III ROV (remotely operated vehicle) is...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
1  As per the information received, the esthetic ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
2  The "K-9 Kannon, P/N 49213" is a tennis ball l...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
3  The good is called the Cobra MK-II and is manu...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
4  This is a plastic, replacement spout for vario...                                                                                                                                                                                                                                                                                                                                                                                      

In [141]:
test2.columns = ['hs code', 'description']
test2

hs code                                        description
0     8479  The UHD-III ROV (remotely operated vehicle) is...
1     8479  As per the information received, the esthetic ...
2     8479  The "K-9 Kannon, P/N 49213" is a tennis ball l...
3     8479  The good is called the Cobra MK-II and is manu...
4     8481  This is a plastic, replacement spout for vario...
5     8481  The good is a plastic threaded valve cap which...
6     8481  This is a hand operated, replacement air relea...
7     8481  Based on the literature provided, part number ...
8     8481  This is a hand operated, replacement fuel valv...
9     8479  The IBC Brand Cleaning Tool, Standard Series, ...

In [142]:
x_test_2_tfidf_vec = tfidf_vec.transform(test2['description'])

In [143]:
y_hat_2 = nb.predict(x_test_2_tfidf_vec)

y_hat_2

array([8479, 8481, 8481, 8479, 8481, 8481, 8414, 8479, 8481, 8479])

In [146]:
test2['hs code'].values

array([8479, 8479, 8479, 8479, 8481, 8481, 8481, 8481, 8481, 8479],
      dtype=int64)

In [145]:
y_hat_3 = lr.predict(x_test_2_tfidf_vec)

y_hat_3

array([8479, 8479, 8479, 8479, 8481, 8479, 8414, 8479, 8479, 8479])